# Generated by Django 4.1.1 on 2022-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao_curta", models.TextField(max_length=255)),
                ("descricao_longa", models.TextField()),
                ("imagem", models.ImageField(upload_to="produto_imagens")),
                ("slug", models.SlugField(unique=True)),
                ("preco_normal", models.FloatField()),
                ("preco_promocao", models.FloatField(default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("V", "Varicao"), ("S", "Simples")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
