# Generated by Django 4.1.1 on 2022-09-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0002_varicao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="varicao",
            options={"verbose_name": "Variação", "verbose_name_plural": "Variações"},
        ),
    ]
