# Generated by Django 4.1.1 on 2022-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0005_alter_varicao_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[("V", "Variável"), ("S", "Simples")], default="V", max_length=1
            ),
        ),
    ]
