# Generated by Django 4.1.1 on 2022-10-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0006_alter_produto_slug_alter_produto_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco_normal",
            field=models.FloatField(verbose_name="Preço"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_promocao",
            field=models.FloatField(default=0, verbose_name="Preço promocional"),
        ),
        migrations.AlterField(
            model_name="varicao",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="varicoes",
                to="produto.produto",
            ),
        ),
    ]
