# Generated by Django 4.1.1 on 2022-10-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0007_alter_produto_preco_normal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=50, null=True)),
                ("preco", models.FloatField()),
                ("preco_promocional", models.FloatField(default=0)),
                ("estoque", models.PositiveIntegerField(default=1)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variacoes",
                        to="produto.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variação",
                "verbose_name_plural": "Variações",
            },
        ),
        migrations.DeleteModel(
            name="Varicao",
        ),
    ]
